export PART=csd3
export DATA_PATH=/rds/user/cs-rami1/rds-t2-cs119/guillem/datasets/data
export NEPTUNE_API_TOKEN="eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiI5OGI3M2NhOS0yZjYyLTQxMTktODYzYS03ZGNiNzAyMzM3OTEifQ=="
export NEPTUNE_PROJECT=cache/cache-llm